# Generated by Django 4.1 on 2023-09-25 10:31

import astroapp.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BhagyankPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bhagyank', models.IntegerField()),
                ('Bhagyank_Prediction_eng', models.CharField(max_length=2000)),
                ('Bhagyank_Prediction_hin', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='CardPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_num', models.IntegerField()),
                ('card_name', models.CharField(max_length=100)),
                ('card_image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('Prediction_Up_eng', models.CharField(max_length=200)),
                ('Prediction_Down_eng', models.CharField(max_length=200)),
                ('Prediction_Up_hin', models.CharField(max_length=200)),
                ('Prediction_Down_hin', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MoolankPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Moolank', models.IntegerField()),
                ('Moolank_Prediction_eng', models.CharField(max_length=3000)),
                ('Moolank_Prediction_hin', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='NumerologyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='Male', max_length=10)),
                ('DOB', models.DateField()),
                ('TOB', models.TimeField()),
                ('POB', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Numerology History',
            },
        ),
        migrations.CreateModel(
            name='TarotCardPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_num', models.IntegerField(blank=True, null=True)),
                ('card_name', models.CharField(max_length=2000)),
                ('card_image', models.FileField(upload_to='images/')),
                ('Prediction_Up_eng', models.CharField(max_length=4000)),
                ('Prediction_Down_eng', models.CharField(max_length=4000)),
                ('Prediction_Up_hin', models.CharField(max_length=4000)),
                ('Prediction_Down_hin', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=30)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', astroapp.models.CustomUserManager()),
            ],
        ),
    ]
