# Generated by Django 4.1 on 2023-11-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KundliData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('place', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
