# Generated by Django 4.2.7 on 2023-12-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroapp', '0003_alter_kundlidata_options_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
