# Generated by Django 4.2.7 on 2023-12-05 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astroapp', '0008_userprofile_otp_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
