# Generated by Django 4.2.7 on 2023-12-05 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astroapp', '0010_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
