# Generated by Django 4.2.7 on 2023-12-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroapp', '0012_alter_customuser_phone_number_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
