# Generated by Django 4.2.7 on 2023-12-06 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astroapp', '0014_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
